export const MOCK_AI_MODEL_CONFIGS = Object.freeze([
  {
    id: 'model_groq_gpt_oss',
    name: 'Groq GPT-OSS',
    provider: 'groq',
    model: 'openai/gpt-oss-20b',
    enabled: true,
    is_default: true,
    credential_status: 'configured',
    default_batch_size: 30,
    max_batch_size: 50,
    max_whole_videos: 30,
    note: 'Fast free-tier model; batching recommended.',
  },
  {
    id: 'model_gemini_flash',
    name: 'Gemini Flash',
    provider: 'google',
    model: 'gemini-flash',
    enabled: true,
    is_default: false,
    credential_status: 'configured',
    default_batch_size: 60,
    max_batch_size: 120,
    max_whole_videos: 80,
    note: 'Larger context option for broader source sets.',
  },
])
