const minutesAgo = minutes => new Date(Date.now() - minutes * 60_000).toISOString()

export function createMockAiRequests(planId) {
  return [
    {
      id: 'air_8f31c2a7',
      plan_id: planId,
      status: 'running',
      model_config_id: 'model_groq_gpt_oss',
      model_snapshot: { name: 'Groq GPT-OSS', provider: 'groq', model: 'openai/gpt-oss-20b' },
      processing_mode: 'batch',
      requested_batch_size: 30,
      effective_batch_size: 28,
      organization_context: { mode: 'title_only', description_max_words: 200, max_tags_per_video: 12 },
      total_videos: 166,
      processed_videos: 56,
      total_batches: 6,
      completed_batches: 2,
      generation_mode: 'llm',
      error_code: null,
      error_message: null,
      created_course_ids: [],
      created_at: minutesAgo(18),
      updated_at: minutesAgo(1),
      started_at: minutesAgo(17),
      completed_at: null,
      selected_sources: [
        { channel_id: 'channel_agents', title: 'AI Engineering', playlists: ['Agent Foundations', 'Production Agents'], video_count: 104 },
        { channel_id: 'channel_python', title: 'Python Academy', playlists: ['LangGraph'], video_count: 62 },
      ],
      batches: [
        { number: 1, video_count: 28, status: 'completed', model: 'openai/gpt-oss-20b', duration_secs: 19 },
        { number: 2, video_count: 28, status: 'completed', model: 'openai/gpt-oss-20b', duration_secs: 22 },
        { number: 3, video_count: 28, status: 'running', model: 'openai/gpt-oss-20b', duration_secs: null },
        { number: 4, video_count: 28, status: 'queued', model: 'openai/gpt-oss-20b', duration_secs: null },
        { number: 5, video_count: 28, status: 'queued', model: 'openai/gpt-oss-20b', duration_secs: null },
        { number: 6, video_count: 26, status: 'queued', model: 'openai/gpt-oss-20b', duration_secs: null },
      ],
      attempts: [
        { number: 1, event: 'Request claimed by worker', status: 'completed', at: minutesAgo(17) },
        { number: 2, event: 'Batch 1 generated', status: 'completed', at: minutesAgo(15) },
        { number: 3, event: 'Batch 2 generated', status: 'completed', at: minutesAgo(8) },
        { number: 4, event: 'Processing batch 3', status: 'running', at: minutesAgo(1) },
      ],
    },
    {
      id: 'air_d540be19',
      plan_id: planId,
      status: 'waiting_for_rate_limit',
      model_config_id: 'model_groq_gpt_oss',
      model_snapshot: { name: 'Groq GPT-OSS', provider: 'groq', model: 'openai/gpt-oss-20b' },
      processing_mode: 'batch',
      requested_batch_size: 30,
      effective_batch_size: 24,
      organization_context: { mode: 'title_tags', description_max_words: 200, max_tags_per_video: 8 },
      total_videos: 82,
      processed_videos: 24,
      total_batches: 4,
      completed_batches: 1,
      generation_mode: 'llm',
      error_code: null,
      error_message: null,
      created_course_ids: [],
      created_at: minutesAgo(64),
      updated_at: minutesAgo(4),
      started_at: minutesAgo(62),
      completed_at: null,
      selected_sources: [
        { channel_id: 'channel_cloud', title: 'Cloud Native Lab', playlists: ['Kubernetes Operators'], video_count: 82 },
      ],
      batches: [
        { number: 1, video_count: 24, status: 'completed', model: 'openai/gpt-oss-20b', duration_secs: 31 },
        { number: 2, video_count: 24, status: 'waiting_for_rate_limit', model: 'openai/gpt-oss-20b', duration_secs: null },
        { number: 3, video_count: 24, status: 'queued', model: 'openai/gpt-oss-20b', duration_secs: null },
        { number: 4, video_count: 10, status: 'queued', model: 'openai/gpt-oss-20b', duration_secs: null },
      ],
      attempts: [
        { number: 1, event: 'Request claimed by worker', status: 'completed', at: minutesAgo(62) },
        { number: 2, event: 'Batch 1 generated', status: 'completed', at: minutesAgo(58) },
        { number: 3, event: 'Provider TPM reached; resume scheduled', status: 'waiting_for_rate_limit', at: minutesAgo(4) },
      ],
    },
    {
      id: 'air_21a70cb4',
      plan_id: planId,
      status: 'completed',
      model_config_id: 'model_gemini_flash',
      model_snapshot: { name: 'Gemini Flash', provider: 'google', model: 'gemini-flash' },
      processing_mode: 'whole',
      requested_batch_size: null,
      effective_batch_size: null,
      organization_context: { mode: 'title_only', description_max_words: 200, max_tags_per_video: 12 },
      total_videos: 30,
      processed_videos: 30,
      total_batches: 1,
      completed_batches: 1,
      generation_mode: 'llm',
      error_code: null,
      error_message: null,
      created_course_ids: ['course_mock_agents', 'course_mock_graphs'],
      created_at: minutesAgo(190),
      updated_at: minutesAgo(184),
      started_at: minutesAgo(189),
      completed_at: minutesAgo(184),
      selected_sources: [
        { channel_id: 'channel_agents', title: 'AI Engineering', playlists: ['Agent Foundations'], video_count: 30 },
      ],
      batches: [
        { number: 1, video_count: 30, status: 'completed', model: 'gemini-flash', duration_secs: 34 },
      ],
      attempts: [
        { number: 1, event: 'Request claimed by worker', status: 'completed', at: minutesAgo(189) },
        { number: 2, event: 'Whole catalog generated', status: 'completed', at: minutesAgo(185) },
        { number: 3, event: 'Two courses saved', status: 'completed', at: minutesAgo(184) },
      ],
    },
    {
      id: 'air_55c092de',
      plan_id: planId,
      status: 'failed',
      model_config_id: 'model_groq_gpt_oss',
      model_snapshot: { name: 'Groq GPT-OSS', provider: 'groq', model: 'openai/gpt-oss-20b' },
      processing_mode: 'whole',
      requested_batch_size: null,
      effective_batch_size: null,
      organization_context: { mode: 'full_metadata', description_max_words: 200, max_tags_per_video: 12 },
      total_videos: 48,
      processed_videos: 0,
      total_batches: 1,
      completed_batches: 0,
      generation_mode: null,
      error_code: 'CAPACITY_EXCEEDED',
      error_message: 'Estimated request exceeds this model capacity. Retry in batch mode.',
      created_course_ids: [],
      created_at: minutesAgo(420),
      updated_at: minutesAgo(419),
      started_at: minutesAgo(419),
      completed_at: minutesAgo(419),
      selected_sources: [
        { channel_id: 'channel_agents', title: 'AI Engineering', playlists: ['Production Agents'], video_count: 48 },
      ],
      batches: [],
      attempts: [
        { number: 1, event: 'Capacity preflight rejected whole mode', status: 'failed', at: minutesAgo(419) },
      ],
    },
  ]
}
